name: Pipeline - Build, Test, and Push Docker Image

on:
  push:
    branches:
      - main  # Change this to your main branch name (if it is different from "main")

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v4.1.1

        with:
          context: MyProject
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/flask_app:latest

  
